In [59]:
import sys
sys.path.append('../')

import numpy as np
import scipy.sparse as ssp
import matplotlib.pyplot as plt
import qutip as qt
import scqubits as scq
from matplotlib.colors import LogNorm
from tqdm import tqdm
from qutip.qip.operations import rz, cz_gate
import cmath
from sympy import symbols
import utils_2Q_gate_zp as ut
# ut.set_fig_font() ### Set various sizes in plotting
import scipy as sp
from joblib import Parallel, delayed
import itertools
from qutip.qip.operations import rz, cz_gate, cnot, rx, hadamard_transform, swap
import pandas as pd

## Prepare two zero pi 

In [60]:
args_all = ut.get_operator_two_zeropi()

In [61]:
[n_theta1, n_theta2, n_theta1_dress, n_theta2_dress, n_theta1_truc, n_theta2_truc,
eval_tot, order_sort, H0, trunc_states, eket0, eket1, eket_tot ] = args_all

truc = len(trunc_states)
state_tot = [qt.basis(truc, i) for i in range(truc)]

# Trans ;  w_ij;    n_theta1; n_theta2; sum
# 00-14 ;  45.925 ;  0.032 ;  0.006 ;  0.038
# 20-14 ;  24.289 ;  0.046 ;  0.001 ;  0.047
logi_space = ['00', '02', '20', '22']
[ w_00_14, w_20_14, n_theta1_00_14, n_theta2_00_14,
n_theta1_20_14, n_theta2_20_14] = ut.get_transition_freq_cnot(args_all)
idxs = [order_sort.index(i) for i in trunc_states]

# H = hadamard_transform()
# I = qt.qeye(2)

In [46]:
=

SyntaxError: invalid syntax (1763773627.py, line 1)

## CNOT transform

In [ ]:
from qutip.qip.operations import rz, cz_gate, cnot, rx, hadamard_transform, swap
from scipy.linalg import kron

# Define 1-qubit gates
I = np.eye(2)
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])

# Standard CNOT (control=0, target=1)
CNOT_01 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

# H ⊗ H
HH = kron(H, H)

# Conjugate to get CNOT(1, 0)
CNOT_10 = HH @ CNOT_01 @ HH

# Optional: round for cleaner display
np.set_printoptions(precision=3, suppress=True)
print("CNOT(0,1):\n", CNOT_01)
print("\nTransformed to CNOT(1,0):\n", CNOT_10)


CNOT(0,1):
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]

Transformed to CNOT(1,0):
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [ ]:
swap()* CNOT_10* swap()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [ ]:
HH

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

In [ ]:
# np.array(np.real(cnot())).tolist()
Uc =   [[0.0, 0.0, 1.0, 0.0],
        [0.0, 1.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0]]
Uc = qt.Qobj(Uc, dims = [[2, 2], [2, 2]])
XI = qt.tensor(qt.sigmax(), qt.qeye(2))
Uc_prime = XI* swap()* Uc* swap()* XI # for |14> state
Uc_prime

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [ ]:
# np.array(np.real(cnot())).tolist()
Uc =   [[1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 1.0, 0.0, 0.0]]
Uc = qt.Qobj(Uc, dims = [[2, 2], [2, 2]])
XI = qt.tensor(qt.sigmax(), qt.qeye(2))
Uc_prime = swap()* Uc* swap() # for |45> state
Uc_prime

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [10]:
arg_de = [ 1.197e-02 , 4.312e-02 , 7.87e+02, -2.755e-02,  -2.147e-02]
# arg_de = [ 1.19684488e-02 , 4.31228037e-02 , 7.87034306e+02, -2.75520928e-02,  -2.14656762e-02]

ut.get_fidelity_cnot_2A0(arg_de, *args)

-0.9999298634615925

In [ ]:
for i in range(len(fidelity)):
    print(i, fidelity[i], t_vec[i],)

0 -0.9077507681745061 499.15999999999997
1 -0.9916068845435732 799.16
2 -0.8585420402926834 1099.1599999999999


## Fidelity calculation

In [ ]:
drive_amp, tg, detune = [0.0058, 777.4, -0.00039]

H_qbt_drive = [ H0, [2*np.pi*N_a_trunc, ut.drive_gauss_A],
                    [2*np.pi*N_a_trunc, ut.drive_gauss_B]  ]
pulse_args = {'drive_amp_A': drive_amp* (na_1_2/na_0_2) , 'drive_freq_A': w_0_2 + 2*np.pi*detune,
              'drive_amp_B': drive_amp , 'drive_freq_B': w_1_2 + 2*np.pi*detune, 'gate_time': tg}

tlist = np.linspace(0, tg, num=3*int(tg))  # total time
prop = qt.propagator(
    H=H_qbt_drive,
    t=tlist,
    args=pulse_args,)[-1]

state_logi = state_tot[:4]
Uc2 = qt.Qobj([ [np.round(prop.matrix_element(s1, s2), 3) for s1 in state_logi]
            for s2 in state_logi  ], dims=[[2, 2], [2, 2]])
print('fidelity: ', ut.cnot_fidelity(prop, state_tot))

print('amplitude:\n',np.abs(np.array(Uc2)))
print('\nphase:\n',np.angle(Uc2))
Uc2

NameError: name 'N_a_trunc' is not defined

## CNOT single qubit z rotations

In [ ]:
XI = qt.tensor(qt.sigmax(), qt.qeye(2))
Uc2_prime = XI* swap()* Uc2* swap()* XI
phase = np.angle(Uc2_prime)

x1 = 0.5* (- phase[1,1] + phase[2,3] - phase[3,2] + phase[0,0])
x2 = 0.5* (  phase[1,1] - phase[2,3] - phase[3,2] + phase[0,0])
x3 = 0.5* (- phase[1,1] - phase[2,3] + phase[3,2] + phase[0,0])
U_bef = qt.Qobj(np.diag([1, np.exp(1j* x1), np.exp(1j* x2), np.exp(1j* (x1+x2))])
        , dims=[[2, 2], [2, 2]])
U_aft = qt.Qobj(np.diag([1, np.exp(1j* x3), 1, np.exp(1j* x3)])
         , dims=[[2, 2], [2, 2]])


# U_final = ut.remove_global_phase( U_bef* Uc2_prime* U_aft)
U_final = np.exp(-1j* phase[0,0])* U_bef* Uc2_prime* U_aft
fidelity = ut.gate_fidelity( cnot(), U_final)
print('fidelity', fidelity)

qt.Qobj(U_final)

fidelity 0.9991895578857666


Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99427836e-01+0.j          2.93180265e-04-0.03104697j
   0.00000000e+00+0.j          0.00000000e+00+0.j        ]
 [-5.68351805e-04-0.03101092j  9.99441844e-01+0.j
   0.00000000e+00+0.j          0.00000000e+00+0.j        ]
 [ 0.00000000e+00+0.j          0.00000000e+00+0.j
   2.29475890e-03-0.01545102j  9.99926497e-01+0.j        ]
 [ 0.00000000e+00+0.j          0.00000000e+00+0.j
   9.99342284e-01+0.j         -5.81681827e-04-0.01522044j]]

## Gate decomposition

In [ ]:
# find closest unitary, code from forest-benchmarking

def proj_choi_to_unitary(choi, check_finite = True):
    """
    Compute the unitary closest to a quantum process specified by a Choi matrix.

    This function enforces Hermiticity of the Choi matrix. See [IntQC]_ for more details:

    .. [IntQC] Interference of Quantum Channels.
        Daniel K. L. Oi.
        Phys. Rev. Lett. 91, 067902 (2003).
        https://doi.org/10.1103/PhysRevLett.91.067902
        https://arxiv.org/abs/quant-ph/0303178

    :param choi: the Choi representation of a quantum process.
    :param check_finite: check that the input matrices contain only finite numbers.
    :return: choi matrix corresponding to the closest unitary
    """
    dim = int(np.sqrt(choi.shape[0]))
    hermitian_choi = (choi + choi.conj().T) / 2  # enforce Hermiticity
    vals, vs = sp.linalg.eigh(hermitian_choi, check_finite=check_finite)

    # vec corresponding to largest eval =  Kraus OP with largest norm
    large_eigen_vec = vs[:, np.argmax(vals)].reshape((dim * dim, 1))
    kraus = unvec(large_eigen_vec)

    U, s, V = sp.linalg.svd(kraus)
    unitary = U @ V
    # pick a global phase convention, we choose the first element
    phase = np.angle(unitary[0, 0])
    return kraus2choi(np.exp(-1j * phase) * unitary)

def vec(matrix):
    """
    Vectorize, or "vec", a matrix by column stacking.

    For example the 2 by 2 matrix A::

        A = [[a, b]
             [c, d]]

    becomes::

      |A>> := vec(A) = (a, c, b, d)^T

    where `|A>>` denotes the vec'ed version of A and :math:`^T` denotes transpose.

    :param matrix: A N (rows) by M (columns) numpy array.
    :return: Returns a column vector with  N by M rows.
    """
    return np.asarray(matrix).T.reshape((-1, 1))


def unvec(vector, shape = None):
    """
    Take a column vector and turn it into a matrix.

    By default, the unvec'ed matrix is assumed to be square. Specifying shape = [N, M] will
    produce a N by M matrix where N is the number of rows and M is the number of columns.

    Consider::

        |A>> := vec(A) = (a, c, b, d)^T

    `unvec(|A>>)` should return::

        A = [[a, b]
             [c, d]]

    :param vector: A (N*M) by 1 numpy array.
    :param shape: The shape of the output matrix; by default, the matrix is assumed to be square.
    :return: Returns a N by M matrix.
    """
    vector = np.asarray(vector)
    if shape is None:
        dim = int(np.sqrt(vector.size))
        shape = dim, dim
    matrix = vector.reshape(*shape).T
    return matrix

def kraus2choi(kraus_ops):
    r"""
    Convert a set of Kraus operators (representing a channel) to
    a Choi matrix using the column stacking convention.

    Suppose the N Kraus operators M_i are dim by dim matrices. Then the
    the Choi matrix is a dim**2 by dim**2 matrix

    .. math::

        \rm{choi\_matrix} = \sum_i^N |M_i>> (|M_i>>)^\dagger = \sum_i^N |M_i>> <<M_i|

    where::

        |M_i>> = vec(M_i)

    :param kraus_ops: A list of N Kraus operators
    :return: Returns a dim**2 by dim**2 matrix.
    """
    if isinstance(kraus_ops, np.ndarray):  # handle input of single kraus op
        if len(kraus_ops[0].shape) < 2:  # first elem is not a matrix
            kraus_ops = [kraus_ops]

    return sum([vec(op) @ vec(op).conj().T for op in kraus_ops])

def choi2kraus(choi, tol = 1e-9):
    """
    Converts a Choi matrix into a list of Kraus operators. ; operators with small norm may be
    excluded.

    :param choi: a dim**2 by dim**2 choi matrix
    :param tol: optional threshold parameter for eigenvalues/kraus ops to be discarded
    :return: list of Kraus operators
    """
    eigvals, v = np.linalg.eigh(choi)
    return [np.lib.scimath.sqrt(eigval) * unvec(np.array([evec]).T) for eigval, evec in
            zip(eigvals, v.T) if abs(eigval) > tol]

In [ ]:
choi_mat = kraus2choi([U_final.full()])

unitary_proj = proj_choi_to_unitary(choi_mat)
good = choi2kraus(unitary_proj)
goodqt = qt.Qobj(np.array(good).reshape([4,4]), dims=[[2, 2], [2, 2]],)

In [ ]:
import cirq as cirq
cz = np.array([[1.0,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,-1]],dtype=np.complex128)

cnot = np.array([[1.0,0,0,0],
             [0,1,0,0],
             [0,0,0,1],
             [0,0,1,0]],dtype=np.complex128)

decomp = cirq.kak_decomposition(goodqt.full())
U1, U2 = decomp.single_qubit_operations_before
U3, U4 = decomp.single_qubit_operations_after
global_phase = decomp.global_phase
txx, tyy, tzz =decomp.interaction_coefficients
Id = np.array([[1.0, 0],[0, 1.0]],dtype=np.complex128)
X = np.array([[0, 1.0],[1.0, 0]],dtype=np.complex128)
Y = np.array([[0, -1j],[1j, 0]],dtype=np.complex128)
Z = np.array([[1.0, 0],[0, -1.0]],dtype=np.complex128)
XX = np.kron(X,X)
YY = np.kron(Y,Y)
ZZ = np.kron(Z,Z)
CAN = sp.linalg.expm(1j*( txx*XX + tyy*YY + tzz*ZZ) )
out1 = global_phase * np.kron(U3,U4) @ CAN @ np.kron(U1,U2)

qt.Qobj(out1)

print(txx,tyy,tzz)
print(np.pi/4)

0.7774594572256055 0.0 -0.0
0.7853981633974483


In [ ]:
u1decomp =cirq.axis_angle(H.full())
print('axis = ', u1decomp.axis)
print('angle = ', u1decomp.angle)
print('global pohase = ', u1decomp.global_phase)

axis =  (0.7071067811865476, -0.0, 0.7071067811865476)
angle =  3.141592653589793
global pohase =  (-0+1j)
